name: 📦 Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/optimix
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: pipx run build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
